### PR TITLE
Add RAM/ROM stats to the application

### PR DESCRIPTION
**Pull request by deepikabhavnani**
Dependent on https://github.com/ARMmbed/mbed-os/pull/8607

### CODE REVIEW

**Comment by deepikabhavnani** [comment]
@kegilbert

**Comment by deepikabhavnani** [comment]
@kegilbert - Please review

**Review by kegilbert — APPROVED** [review]
LGTM! Sorry for the delay.

**Comment by kegilbert** [comment]
@deepikabhavnani Is this waiting on anything else?

**Pull request merged**
